function(iop_catalog_sources manifest output)
    if(NOT EXISTS "${manifest}")
        message(FATAL_ERROR "IOP catalog manifest does not exist")
    endif()
    file(SIZE "${manifest}" manifest_bytes)
    if(manifest_bytes GREATER 16777216)
        message(FATAL_ERROR "IOP catalog manifest exceeds 16 MiB")
    endif()
    file(READ "${manifest}" catalog)
    string(JSON schema ERROR_VARIABLE schema_error GET "${catalog}" schema_version)
    string(JSON schema_type ERROR_VARIABLE schema_type_error TYPE "${catalog}" schema_version)
    string(JSON symbol ERROR_VARIABLE symbol_error GET "${catalog}" symbol)
    string(JSON sources_type ERROR_VARIABLE type_error TYPE "${catalog}" sources)
    if(schema_error OR schema_type_error OR symbol_error OR type_error OR NOT schema STREQUAL "1" OR
       NOT schema_type STREQUAL "NUMBER" OR
       NOT symbol STREQUAL "compiledIopProgram" OR NOT sources_type STREQUAL "ARRAY")
        message(FATAL_ERROR "Invalid IOP catalog schema/symbol/sources")
    endif()
    string(JSON count LENGTH "${catalog}" sources)
    if(count LESS 1)
        message(FATAL_ERROR "IOP catalog has no sources")
    endif()
    get_filename_component(manifest_absolute "${manifest}" ABSOLUTE)
    get_filename_component(directory "${manifest_absolute}" DIRECTORY)
    math(EXPR last "${count} - 1")
    set(sources)
    foreach(index RANGE 0 ${last})
        string(JSON name_type TYPE "${catalog}" sources ${index})
        string(JSON name GET "${catalog}" sources ${index})
        if(NOT name_type STREQUAL "STRING" OR NOT name MATCHES "^[A-Za-z0-9_-]+\\.cpp$")
            message(FATAL_ERROR "IOP catalog source is not a generated C++ basename")
        endif()
        if(NOT EXISTS "${directory}/${name}")
            message(FATAL_ERROR "IOP catalog source does not exist")
        endif()
        list(APPEND sources "${directory}/${name}")
    endforeach()
    list(REMOVE_DUPLICATES sources)
    list(LENGTH sources unique_count)
    if(NOT unique_count EQUAL count)
        message(FATAL_ERROR "IOP catalog contains duplicate sources")
    endif()
    set(verified_files ${sources} "${directory}/iop_native_semantics.h")
    foreach(source IN LISTS verified_files)
        get_filename_component(name "${source}" NAME)
        string(JSON expected ERROR_VARIABLE hash_error GET "${catalog}" sha256 "${name}")
        string(LENGTH "${expected}" hash_length)
        if(hash_error OR NOT hash_length EQUAL 64 OR NOT expected MATCHES "^[0-9a-f]+$" OR
           NOT EXISTS "${source}" OR IS_DIRECTORY "${source}")
            message(FATAL_ERROR "IOP catalog source identity is missing/invalid")
        endif()
        file(SHA256 "${source}" actual)
        if(NOT actual STREQUAL expected)
            message(FATAL_ERROR "IOP catalog source differs from its manifest")
        endif()
    endforeach()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest_absolute}" ${verified_files})
    set(${output} "${sources}" PARENT_SCOPE)
endfunction()
