function(ee_family_catalog_sources manifest output)
    if(NOT EXISTS "${manifest}" OR IS_SYMLINK "${manifest}" OR IS_DIRECTORY "${manifest}")
        message(FATAL_ERROR "EE family manifest must be an ordinary file")
    endif()
    file(SIZE "${manifest}" bytes)
    if(bytes GREATER 16777216)
        message(FATAL_ERROR "EE family manifest exceeds budget")
    endif()
    file(READ "${manifest}" catalog)
    foreach(field IN ITEMS schema_version symbol strict_approval closure_proved sources sha256 family_count)
        string(JSON field_type ERROR_VARIABLE type_error TYPE "${catalog}" "${field}")
        if(field STREQUAL "schema_version" OR field STREQUAL "family_count")
            set(required_type NUMBER)
        elseif(field STREQUAL "strict_approval" OR field STREQUAL "closure_proved")
            set(required_type BOOLEAN)
        elseif(field STREQUAL "symbol")
            set(required_type STRING)
        elseif(field STREQUAL "sources")
            set(required_type ARRAY)
        else()
            set(required_type OBJECT)
        endif()
        if(type_error OR NOT field_type STREQUAL required_type)
            message(FATAL_ERROR "Invalid EE family manifest field type: ${field}")
        endif()
    endforeach()
    string(JSON schema ERROR_VARIABLE error GET "${catalog}" schema_version)
    string(JSON symbol ERROR_VARIABLE symbol_error GET "${catalog}" symbol)
    string(JSON approval ERROR_VARIABLE approval_error GET "${catalog}" strict_approval)
    string(JSON closure GET "${catalog}" closure_proved)
    string(JSON count ERROR_VARIABLE count_error LENGTH "${catalog}" sources)
    string(JSON families ERROR_VARIABLE families_error GET "${catalog}" family_count)
    if(error OR symbol_error OR approval_error OR count_error OR families_error OR
       NOT schema MATCHES "^[12]$" OR NOT symbol STREQUAL "compiledEeFamilyProgram" OR approval OR closure OR
       NOT families MATCHES "^[1-9][0-9]*$" OR
       families LESS 1 OR families GREATER 32768)
        message(FATAL_ERROR "Invalid experimental EE family manifest")
    endif()
    if(schema STREQUAL "2")
        string(JSON count_type ERROR_VARIABLE source_count_error TYPE "${catalog}" source_count)
        string(JSON required ERROR_VARIABLE required_error GET "${catalog}" source_count)
        if(source_count_error OR required_error OR NOT count_type STREQUAL "NUMBER" OR
           NOT required MATCHES "^[1-9][0-9]*$" OR required LESS 2 OR required GREATER 32769)
            message(FATAL_ERROR "Invalid batched EE family source count")
        endif()
        string(JSON records_type ERROR_VARIABLE records_error TYPE "${catalog}" families)
        string(JSON records_count ERROR_VARIABLE records_count_error LENGTH "${catalog}" families)
        if(records_error OR records_count_error OR NOT records_type STREQUAL "ARRAY" OR NOT records_count EQUAL families)
            message(FATAL_ERROR "EE family descriptor dimensions differ")
        endif()
        math(EXPR maximum "${families}+1")
        if(required GREATER maximum)
            message(FATAL_ERROR "EE family source count exceeds family dimensions")
        endif()
    else()
        if(families GREATER 512)
            message(FATAL_ERROR "Legacy EE family catalog exceeds its budget")
        endif()
        math(EXPR required "${families}+1")
    endif()
    if(NOT count EQUAL required)
        message(FATAL_ERROR "EE family manifest dimensions differ")
    endif()
    get_filename_component(directory "${manifest}" DIRECTORY)
    get_filename_component(ancestor "${directory}" ABSOLUTE)
    while(TRUE)
        if(IS_SYMLINK "${ancestor}")
            message(FATAL_ERROR "EE family catalog ancestry must not be a symlink")
        endif()
        get_filename_component(parent "${ancestor}" DIRECTORY)
        if(parent STREQUAL ancestor)
            break()
        endif()
        set(ancestor "${parent}")
    endwhile()
    set(sources "")
    set(index_count 0)
    # CMake parses JSON anew on each query. Extract the small source indexes
    # once rather than reparsing the full numerical family ledger per file.
    string(JSON source_names GET "${catalog}" sources)
    string(JSON source_hashes GET "${catalog}" sha256)
    math(EXPR last "${count}-1")
    foreach(index RANGE 0 ${last})
        string(JSON name_type TYPE "${source_names}" ${index})
        if(NOT name_type STREQUAL "STRING")
            message(FATAL_ERROR "EE family source name must be a string")
        endif()
        string(JSON name GET "${source_names}" ${index})
        if(name STREQUAL "ee_family_catalog.cpp")
            math(EXPR index_count "${index_count}+1")
            set(source_limit 8388608)
        else()
            set(source_limit 1048576)
            string(LENGTH "${name}" name_length)
            if(NOT name_length EQUAL 78 OR NOT name MATCHES "^ee_family_[0-9a-f]+[.]cpp$")
                message(FATAL_ERROR "Invalid EE family source name")
            endif()
        endif()
        if(NOT EXISTS "${directory}/${name}" OR IS_SYMLINK "${directory}/${name}" OR IS_DIRECTORY "${directory}/${name}")
            message(FATAL_ERROR "Missing or linked EE family source")
        endif()
        file(SIZE "${directory}/${name}" source_bytes)
        if(source_bytes GREATER source_limit)
            message(FATAL_ERROR "EE family source exceeds budget")
        endif()
        string(JSON hash_type ERROR_VARIABLE hash_type_error TYPE "${source_hashes}" "${name}")
        string(JSON expected ERROR_VARIABLE hash_error GET "${source_hashes}" "${name}")
        string(LENGTH "${expected}" length)
        file(SHA256 "${directory}/${name}" actual)
        if(hash_type_error OR NOT hash_type STREQUAL "STRING" OR hash_error OR NOT length EQUAL 64 OR NOT expected MATCHES "^[0-9a-f]+$" OR NOT expected STREQUAL actual)
            message(FATAL_ERROR "EE family source differs from manifest")
        endif()
        list(APPEND sources "${directory}/${name}")
    endforeach()
    list(REMOVE_DUPLICATES sources)
    list(LENGTH sources unique)
    if(NOT unique EQUAL count OR NOT index_count EQUAL 1)
        message(FATAL_ERROR "Duplicate or missing EE family catalog index")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}" ${sources})
    # Preserve source/object paths across fresh job directories. Headers and
    # compiler flags still participate in the build system's normal dependency
    # checks; a matching source digest alone never qualifies guest semantics.
    set(cache "${CMAKE_BINARY_DIR}/ee-family-source-cache")
    file(MAKE_DIRECTORY "${cache}")
    if(IS_SYMLINK "${cache}")
        message(FATAL_ERROR "EE family source cache must be ordinary")
    endif()
    set(cached "")
    foreach(source IN LISTS sources)
        file(SHA256 "${source}" digest)
        get_filename_component(name "${source}" NAME)
        string(JSON expected GET "${source_hashes}" "${name}")
        if(NOT digest STREQUAL expected)
            message(FATAL_ERROR "EE family source changed before cache publication")
        endif()
        set(destination "${cache}/ee_family_${digest}.cpp")
        if(IS_SYMLINK "${destination}" OR IS_DIRECTORY "${destination}")
            message(FATAL_ERROR "EE family cached source must be ordinary")
        endif()
        if(NOT EXISTS "${destination}")
            configure_file("${source}" "${destination}" COPYONLY)
        endif()
        file(SHA256 "${destination}" cached_digest)
        if(NOT digest STREQUAL cached_digest)
            message(FATAL_ERROR "EE family cached source identity differs")
        endif()
        list(APPEND cached "${destination}")
    endforeach()
    set(${output} "${cached}" PARENT_SCOPE)
endfunction()
