function(ee_family_catalog_sources manifest output)
    if(NOT EXISTS "${manifest}" OR IS_SYMLINK "${manifest}" OR IS_DIRECTORY "${manifest}")
        message(FATAL_ERROR "EE family manifest must be an ordinary file")
    endif()
    file(SIZE "${manifest}" bytes)
    if(bytes GREATER 16777216)
        message(FATAL_ERROR "EE family manifest exceeds budget")
    endif()
    file(READ "${manifest}" catalog)
    foreach(field IN ITEMS schema_version symbol strict_approval closure_proved sources sha256 family_count)
        string(JSON field_type ERROR_VARIABLE type_error TYPE "${catalog}" "${field}")
        if(field STREQUAL "schema_version" OR field STREQUAL "family_count")
            set(required_type NUMBER)
        elseif(field STREQUAL "strict_approval" OR field STREQUAL "closure_proved")
            set(required_type BOOLEAN)
        elseif(field STREQUAL "symbol")
            set(required_type STRING)
        elseif(field STREQUAL "sources")
            set(required_type ARRAY)
        else()
            set(required_type OBJECT)
        endif()
        if(type_error OR NOT field_type STREQUAL required_type)
            message(FATAL_ERROR "Invalid EE family manifest field type: ${field}")
        endif()
    endforeach()
    string(JSON schema ERROR_VARIABLE error GET "${catalog}" schema_version)
    string(JSON symbol ERROR_VARIABLE symbol_error GET "${catalog}" symbol)
    string(JSON approval ERROR_VARIABLE approval_error GET "${catalog}" strict_approval)
    string(JSON closure GET "${catalog}" closure_proved)
    string(JSON count ERROR_VARIABLE count_error LENGTH "${catalog}" sources)
    string(JSON families ERROR_VARIABLE families_error GET "${catalog}" family_count)
    if(error OR symbol_error OR approval_error OR count_error OR families_error OR
       NOT schema STREQUAL "1" OR NOT symbol STREQUAL "compiledEeFamilyProgram" OR approval OR closure OR
       NOT families MATCHES "^[1-9][0-9]*$" OR
       families LESS 1 OR families GREATER 512)
        message(FATAL_ERROR "Invalid experimental EE family manifest")
    endif()
    math(EXPR required "${families}+1")
    if(NOT count EQUAL required)
        message(FATAL_ERROR "EE family manifest dimensions differ")
    endif()
    get_filename_component(directory "${manifest}" DIRECTORY)
    get_filename_component(ancestor "${directory}" ABSOLUTE)
    while(TRUE)
        if(IS_SYMLINK "${ancestor}")
            message(FATAL_ERROR "EE family catalog ancestry must not be a symlink")
        endif()
        get_filename_component(parent "${ancestor}" DIRECTORY)
        if(parent STREQUAL ancestor)
            break()
        endif()
        set(ancestor "${parent}")
    endwhile()
    set(sources "")
    set(index_count 0)
    math(EXPR last "${count}-1")
    foreach(index RANGE 0 ${last})
        string(JSON name_type TYPE "${catalog}" sources ${index})
        if(NOT name_type STREQUAL "STRING")
            message(FATAL_ERROR "EE family source name must be a string")
        endif()
        string(JSON name GET "${catalog}" sources ${index})
        if(name STREQUAL "ee_family_catalog.cpp")
            math(EXPR index_count "${index_count}+1")
        else()
            string(LENGTH "${name}" name_length)
            if(NOT name_length EQUAL 78 OR NOT name MATCHES "^ee_family_[0-9a-f]+[.]cpp$")
                message(FATAL_ERROR "Invalid EE family source name")
            endif()
        endif()
        if(NOT EXISTS "${directory}/${name}" OR IS_SYMLINK "${directory}/${name}" OR IS_DIRECTORY "${directory}/${name}")
            message(FATAL_ERROR "Missing or linked EE family source")
        endif()
        file(SIZE "${directory}/${name}" source_bytes)
        if(source_bytes GREATER 1048576)
            message(FATAL_ERROR "EE family source exceeds budget")
        endif()
        string(JSON hash_type ERROR_VARIABLE hash_type_error TYPE "${catalog}" sha256 "${name}")
        string(JSON expected ERROR_VARIABLE hash_error GET "${catalog}" sha256 "${name}")
        string(LENGTH "${expected}" length)
        file(SHA256 "${directory}/${name}" actual)
        if(hash_type_error OR NOT hash_type STREQUAL "STRING" OR hash_error OR NOT length EQUAL 64 OR NOT expected MATCHES "^[0-9a-f]+$" OR NOT expected STREQUAL actual)
            message(FATAL_ERROR "EE family source differs from manifest")
        endif()
        list(APPEND sources "${directory}/${name}")
    endforeach()
    list(REMOVE_DUPLICATES sources)
    list(LENGTH sources unique)
    if(NOT unique EQUAL count OR NOT index_count EQUAL 1)
        message(FATAL_ERROR "Duplicate or missing EE family catalog index")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}" ${sources})
    set(${output} "${sources}" PARENT_SCOPE)
endfunction()
