function(ee_catalog_sources manifest output)
    if(NOT EXISTS "${manifest}")
        message(FATAL_ERROR "EE catalog manifest does not exist")
    endif()
    file(SIZE "${manifest}" bytes)
    if(bytes GREATER 16777216)
        message(FATAL_ERROR "EE catalog exceeds 16 MiB")
    endif()
    file(READ "${manifest}" catalog)
    string(JSON schema ERROR_VARIABLE error GET "${catalog}" schema_version)
    string(JSON schema_type ERROR_VARIABLE schema_type_error TYPE "${catalog}" schema_version)
    string(JSON symbol ERROR_VARIABLE symbol_error GET "${catalog}" symbol)
    string(JSON type ERROR_VARIABLE type_error TYPE "${catalog}" sources)
    if(error OR schema_type_error OR symbol_error OR type_error OR NOT schema STREQUAL "1" OR
       NOT schema_type STREQUAL "NUMBER" OR
       NOT symbol STREQUAL "compiledEeProgram" OR NOT type STREQUAL "ARRAY")
        message(FATAL_ERROR "Invalid EE catalog schema/symbol/sources")
    endif()
    string(JSON count LENGTH "${catalog}" sources)
    if(count LESS 2 OR count GREATER 513)
        message(FATAL_ERROR "EE catalog source count outside bounds")
    endif()
    string(JSON bank_type ERROR_VARIABLE bank_type_error TYPE "${catalog}" banks)
    if(bank_type_error OR NOT bank_type STREQUAL "ARRAY")
        message(FATAL_ERROR "EE catalog banks must be an array")
    endif()
    string(JSON banks LENGTH "${catalog}" banks)
    math(EXPR required_sources "${banks}+1")
    if(banks LESS 1 OR banks GREATER 512 OR NOT count EQUAL required_sources)
        message(FATAL_ERROR "EE catalog bank/source counts differ")
    endif()
    get_filename_component(absolute "${manifest}" ABSOLUTE)
    get_filename_component(directory "${absolute}" DIRECTORY)
    math(EXPR last "${count}-1")
    set(sources)
    set(index_count 0)
    foreach(index RANGE 0 ${last})
        string(JSON name GET "${catalog}" sources ${index})
        string(JSON name_type TYPE "${catalog}" sources ${index})
        if(NOT name_type STREQUAL "STRING" OR NOT name MATCHES "^ee_[a-zA-Z0-9_]+\\.cpp$" OR NOT EXISTS "${directory}/${name}" OR
           IS_DIRECTORY "${directory}/${name}")
            message(FATAL_ERROR "EE catalog source is not a generated C++ basename")
        endif()
        if(name STREQUAL "ee_catalog.cpp")
            math(EXPR index_count "${index_count}+1")
        elseif(NOT name MATCHES "^ee_bank_[0-9a-f]+\\.cpp$")
            message(FATAL_ERROR "EE catalog contains an unrecognized bank source")
        endif()
        string(JSON expected ERROR_VARIABLE hash_error GET "${catalog}" sha256 "${name}")
        string(LENGTH "${expected}" length)
        file(SHA256 "${directory}/${name}" actual)
        if(hash_error OR NOT length EQUAL 64 OR NOT expected MATCHES "^[0-9a-f]+$" OR
           NOT expected STREQUAL actual)
            message(FATAL_ERROR "EE catalog source differs from its manifest")
        endif()
        list(APPEND sources "${directory}/${name}")
    endforeach()
    list(REMOVE_DUPLICATES sources)
    list(LENGTH sources unique)
    if(NOT count EQUAL unique OR NOT index_count EQUAL 1)
        message(FATAL_ERROR "EE catalog contains duplicate sources")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${absolute}" ${sources})
    set(${output} "${sources}" PARENT_SCOPE)
endfunction()
