# Optional, explicit source checkout. No network or system package mutations.
set(PS2X_PARALLEL_GS_SOURCE_DIR "" CACHE PATH "Pinned paraLLEl-GS checkout with standalone dependencies")
if(NOT EXISTS "${PS2X_PARALLEL_GS_SOURCE_DIR}/gs/gs_interface.hpp" OR
   NOT EXISTS "${PS2X_PARALLEL_GS_SOURCE_DIR}/Granite/third_party/volk/volk.h" OR
   NOT EXISTS "${PS2X_PARALLEL_GS_SOURCE_DIR}/Granite/third_party/khronos/vulkan-headers/include/vulkan/vulkan.h")
    message(FATAL_ERROR "PS2X_PARALLEL_GS_SOURCE_DIR requires paraLLEl-GS, Granite, volk and Vulkan-Headers")
endif()
set(PARALLEL_GS_STANDALONE ON CACHE BOOL "" FORCE)
set(GRANITE_TOOLS OFF CACHE BOOL "" FORCE)
set(GRANITE_INSTALL_TARGETS OFF CACHE BOOL "" FORCE)
if(NOT TARGET parallel-gs)
    add_subdirectory("${PS2X_PARALLEL_GS_SOURCE_DIR}" "${CMAKE_BINARY_DIR}/parallel-gs-dependency" EXCLUDE_FROM_ALL)
endif()
include("${CMAKE_CURRENT_LIST_DIR}/parallel_gs_compat.cmake")
add_library(ps2_gs_parallel STATIC "${CMAKE_CURRENT_LIST_DIR}/../src/lib/gs/gs_parallel_device.cpp")
target_include_directories(ps2_gs_parallel PUBLIC "${CMAKE_CURRENT_LIST_DIR}/../include")
target_compile_features(ps2_gs_parallel PUBLIC cxx_std_20)
target_link_libraries(ps2_gs_parallel PRIVATE parallel-gs)
set_property(TARGET ps2_gs_parallel PROPERTY INTERPROCEDURAL_OPTIMIZATION FALSE)
add_library(ps2_gs_parallel_backend STATIC "${CMAKE_CURRENT_LIST_DIR}/../src/lib/gs/gs_parallel_backend.cpp")
target_include_directories(ps2_gs_parallel_backend PUBLIC "${CMAKE_CURRENT_LIST_DIR}/../include")
target_compile_features(ps2_gs_parallel_backend PUBLIC cxx_std_20)
target_link_libraries(ps2_gs_parallel_backend PUBLIC ps2_gs_parallel)
set_property(TARGET ps2_gs_parallel_backend PROPERTY INTERPROCEDURAL_OPTIMIZATION FALSE)
